{% set name = "jupyter_server_ydoc" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4fda7f43d0752453e96621f7e7883eed0091146deed0ee38c2fe5f82c69b3f5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.4.0
  run:
    - python
    - jupyter_server >=2.15.0,<3.0.0
    - jupyter_ydoc >=2.1.2,<4.0.0,!=3.0.0,!=3.0.1
    - pycrdt
    - pycrdt-websocket >=0.15.0,<0.16.0
    - jupyter_events >=0.11.0
    - jupyter_server_fileid >=0.7.0,<1
    - jsonschema >=4.18.0

test:
  source_files:
    - tests
  imports:
    - jupyter_server_ydoc
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest >=7.0
    - pytest-jupyter-server
    - jupyter_server_fileid

about:
  home: https://github.com/jupyterlab/jupyter_collaboration
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter Server Extension providing support for Y documents.
  description: Jupyter Server YDoc is a Jupyter Server Extension providing support for Y documents. (Note renamed to jupyter_collaboration)
  dev_url: https://github.com/jupyterlab/jupyter_collaboration
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
