{% set version = "0.1.6" %}

package:
  name: jupyter_server_ydoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_server_ydoc/jupyter_server_ydoc-{{ version }}.tar.gz
  sha256: d9ffc76d37626e0afde84778ec19e9877fe0898265dedf270f65dde7ac7348ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - hatchling >=0.25
    - pip
    - python >=3.7

  run:
    - python >=3.7
    - jupyter_server
    - jupyter_ydoc >=0.1.13
    - ypy-websocket >=0.1.13

test:
  imports:
    - jupyter_server_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_server_ydoc
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Server Extension providing support for Y documents.
  doc_url: https://github.com/jupyter-server/jupyter_server_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
