{% set version = "0.1.12" %}

package:
  name: jupyter_server_ydoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_server_ydoc/jupyter_server_ydoc-{{ version }}.tar.gz
  sha256: 1e912f7450ec99320a99ee8f40bbf1345b1b78f0b5b041ecbfc2d081ff6ed563

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - hatchling >=0.25
    - pip
    - python >=3.7

  run:
    - python >=3.7
    - jupyter_server
    - jupyter_ydoc >=0.1.16,<0.2.0
    - ypy-websocket >=0.3.2,<0.4.0

test:
  imports:
    - jupyter_server_ydoc

about:
  home: https://github.com/jupyter-server/jupyter_server_ydoc
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Server Extension providing support for Y documents.
  doc_url: https://github.com/jupyter-server/jupyter_server_ydoc

extra:
  recipe-maintainers:
    - davidbrochart
