{% set name = "jupyter_server_ydoc" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b526be684aa621ebfd972c18a54ca7c613c67f2d051cf52d7a26aa092f735a46

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling >=1.4.0
  run:
    - python
    - jupyter_server >=2.15.0,<3.0.0
    - jupyter_ydoc >=2.1.2,<4.0.0,!=3.0.0,!=3.0.1
    - pycrdt
    - pycrdt-websocket >=0.15.0,<0.16.0
    - jupyter_events >=0.11.0
    - jupyter_server_fileid >=0.7.0,<1
    - jsonschema >=4.18.0

# Unable to run pytests. $SRC_DIR/jupyter_server_ydoc/pytest_plugin.py needs httpx_ws, which is not available in the main channel.
test:
  imports:
    - jupyter_server_ydoc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-collaboration
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter Server Extension providing support for Y documents.
  description: Jupyter Server YDoc is a Jupyter Server Extension providing support for Y documents. (Note renamed to jupyter_collaboration)
  dev_url: https://github.com/jupyterlab/jupyter-collaboration/tree/main/projects/jupyter-server-ydoc/jupyter_server_ydoc
  doc_url: https://jupyterlab-realtime-collaboration.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server